darkoob/migration/urls.py
from django.conf.urls import patterns, include, url
from darkoob.migration import views as migration_views

urlpatterns = patterns('',
    url(r'^migration/new$', migration_views.start_new_migration, name='new_migration'),
)

darkoob/social/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.auth import views as auth_views

from darkoob.social import views as social_views
from darkoob.social.forms import AuthenticationFormPlaceholder

urlpatterns = patterns('',
    url(r'^home/$', social_views.home, name='home'),
    url(r'^home/stream/$', social_views.home_stream, name='home_stream'),
    url(r'^signup/$', social_views.signup, name='signup'),
    url(r'^login/$', auth_views.login,
        {'template_name': 'social/login.html',
         'authentication_form': AuthenticationFormPlaceholder
        }, name='login'),
    url(r'^logout/$', auth_views.logout_then_login, name='logout'),
    url(r'^change_password/$', social_views.change_password, name='change_password'),
    url(r'^profile/$', social_views.profile, name='profile'),

    url(r'^password/reset/$', auth_views.password_reset, 
        {'post_reset_redirect': 'password/reset/done/'}, name='reset_pass'),
    url(r'^password/reset/done/$', auth_views.password_reset_done),
    url(r'^password/reset/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$', auth_views.password_reset_confirm, 
        {'post_reset_redirect': 'password/done/'}),
    url(r'^password/done/$', auth_views.password_reset_complete),

    url(r'^post/new/$', social_views.new_post, name='new_post'),
    url(r'^user/(?P<username>\w+)/$', social_views.user_profile, name='user_profile'),

    url(r'^user/(?P<username>\w+)/following$', social_views.user_following, name='user_following'),
    url(r'^user/(?P<username>\w+)/followers$', social_views.user_followers, name='user_followers'),
    url(r'^user/(?P<username>\w+)/favorite_books$', social_views.user_favorite_books, name='user_favorite_books'),

    url(r'^profile/followers/$', social_views.followers, name='followers'),
    url(r'^profile/following/$', social_views.following, name='following'),
    url(r'^profile/favorite_books$', social_views.favorite_books, name='favorite_books'),
)

darkoob/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from dajaxice.core import dajaxice_autodiscover, dajaxice_config

from darkoob import views 
from darkoob import ajax 


dajaxice_autodiscover()
admin.autodiscover()

urlpatterns = patterns('',
    # search url
    url(r'^search/', include('haystack.urls')),
    # Django Admin
    url(r'^admin/', include(admin.site.urls)),

    # Static URL
    url(r'', include('django.contrib.staticfiles.urls')),

    # Dajaxice URLs 
    url(r'^ajaxice', views.index),
    url(dajaxice_config.dajaxice_url, include('dajaxice.urls')),

    # Project-specific URLs
    url(r'^$', views.index, name='index'),
    url(r'', include('darkoob.social.urls', namespace='social', app_name='socials')),
    url(r'', include('darkoob.migration.urls', namespace='migration')),

    url(r'^book/', include('darkoob.book.urls', namespace='book')),
    url(r'^group/', include('darkoob.group.urls', namespace='group')),
    # Search 
    # TODO: Move to search application
    url(r'', include('darkoob.search.urls', namespace='search')),

    # url(r'^comments/', include('django.contrib.comments.urls')),

    url(r'^avatar/', include('avatar.urls')),
)

from django.conf import settings
media_root = getattr(settings, 'MEDIA_ROOT', '/media')    

urlpatterns += patterns('', 
url(r'^media/(?P<path>.*)$','django.views.static.serve',
    {'document_root': media_root})
)

darkoob/migration/models.py
from django.db import models
from django.contrib.auth.models import User
from darkoob.book.models import Book

class Hop(models.Model):
    migration = models.ForeignKey('Migration')
    host = models.ForeignKey(User, related_name='host_set', db_index=True)
    received_time = models.DateTimeField(auto_now_add=True, db_index=True)

    class Meta:
        unique_together = (("migration", "host"),)

    def __unicode__(self):
        return unicode("%s - %s" % (self.migration, self.host.username))

class Migration(models.Model):
    book = models.ForeignKey(Book, related_name='book_set')
    starter = models.ForeignKey(User, related_name='starter_set')
    starter_message = models.TextField()
    start_time = models.DateTimeField(auto_now_add=True, db_index=True)
    private_key = models.CharField(max_length=10, unique=True)
 
    def get_user_hoped_migrations(self, user):
        '''return all migration's objects that hoped in user'''
        return [hop.migration for hop in Hop.objects.filter(host=user)]

    def get_user_host_migrations(self, user):
        '''return all migration's objects that hosted by user'''
        return [migrate for migrate in Migration.objects.filter(starter=user)]

    def get_user_related_migrations(self, user):
        '''return get_user_host_migrations() +  get_user_hoped_migrations()'''
        return self.get_user_hoped_migrations(user) + self.get_user_host_migrations(user)

    def __unicode__(self):
        return unicode("%s - %s" % (self.book.title, self.starter.username))

darkoob/social/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from neomodel import StructuredNode, IntegerProperty, RelationshipTo, RelationshipFrom
from darkoob.book.models import Quote, Book

import datetime
from django.utils.timezone import utc
GENDER_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female'),
)


def node(self):
    '''return node of a User'''
    
    return UserNode.index.get(user_id=self.id) 
User.add_to_class('node', node) 

class UserNode(StructuredNode):
    user_id = IntegerProperty(required=True, index=True)
    following = RelationshipTo('UserNode', 'FOLLOW')
    followers = RelationshipFrom('UserNode', 'FOLLOW')

    def user(self):
        ''' return user object of a node '''
        return User.objects.get(id=user_id)

    def follow_person(self, user_id):
        ''' follow person that user.id=user_id'''
        followed_user = self.index.get(user_id=user_id)
        self.following.connect(followed_user, {'time': str(datetime.datetime.utcnow())})

    def is_following(self, user_id): 
        ''' return True if user in self.following.all() else False '''
        user = self.index.get(user_id=user_id)
        return True if user in self.following.all() else False

    def is_followers(self, user_id):
        ''' return True if user in self.followers.all() else False '''
        user = self.index.get(user_id=user_id)
        return True if user in self.followers.all() else False

    def get_following_list(self):
        ''' return list of all user_id that followed by this user '''
        return [user.user_id for user in self.following.all()]



class Country(models.Model):
    name = models.CharField(max_length=50)

    def __unicode__(self):
        return self.name 

class City(models.Model):
    name = models.CharField(max_length=50)
    country = models.OneToOneField(Country)

    def __unicode__(self):
        return self.name 

class UserProfile(models.Model):
    user = models.OneToOneField(User, db_index=True)
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES)
    birthday = models.DateField(null=True)
    mobile = models.CharField(max_length=20, null=True, blank=True)
    website = models.URLField(null=True, blank=True)
    city = models.OneToOneField(City, null=True, blank=True)
    quote = models.ForeignKey(Quote, null=True, blank=True)
    favorite_books = models.ManyToManyField(Book, null=True, blank=True)

    # for django model
    # def favorite_books(self):
    #     return ', '.join([a.title for a in self.favorite_books.all()])
    # favorite_books.short_description = "Favorite Book"

    # NOTE: userprof_obj.education_set.all() return all education set of a person 

    # def get_related_migrations(self):
    #     from darkoob.migration.models import Migration, Hop
    #     print Hop.objects.filter(host=user)

    def node(self):
        '''return node of a UserProfile'''
        return UserNode.index.get(user_id=user.id) 
    def __unicode__(self):
        return self.user.get_full_name()

class School(models.Model):
    name = models.CharField(max_length=50)

    def __unicode__(self):
        return self.name 

class Education(models.Model):
    user_profile = models.ForeignKey(UserProfile, related_name='education_set')
    school = models.OneToOneField(School)

    def __unicode__(self):
        return unicode(self.school)

def create_user_profile(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)
        UserNode(user_id=instance.id).save()
        print "a node with user_id %d created!" % instance.id


post_save.connect(create_user_profile, sender=User)

darkoob/social/forms.py
from django import forms
from django.utils.translation import ugettext as _
from django.core.validators import validate_email
from django.contrib.auth.forms import AuthenticationForm

GENDER_CHOICES = (
    ('Male', 'Male'),
    ('Female', 'Female'),
)
MONTH_CHOICES = (
    (1, 'January'),
    (2, 'February'),
    (3, 'March'),
    (4, 'April'),
    (5, 'May'),
    (6, 'June'),
    (7, 'July'),
    (8, 'August'),
    (9, 'September'),
    (10, 'October'),
    (11, 'November'),
    (12, 'December'),
)
class CommentForm(forms.Form):
    author = forms.CharField()
    comment = forms.CharField()
    parent_id = forms.CharField(widget=forms.HiddenInput())


class AuthenticationFormPlaceholder(AuthenticationForm):
    username = forms.CharField(
        max_length=30,
        widget=forms.TextInput(attrs={
            'id': 'id_username_auth',
            'placeholder': _('Username or Email'),
            'class': 'input-medium',
            'required': '',
        })
    )
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={
            'id': 'id_password_auth',
            'placeholder': _('Password'),
            'class': 'input-medium required',
            'required': '',
        })
    )

class EditProfileForm(forms.Form):
    month = forms.ChoiceField(
        choices = MONTH_CHOICES
    )

    day = forms.CharField(
        label = _('Day'),
        min_length = 1,
        max_length = 2,
        widget = forms.TextInput(attrs={
            'placeholder':_('Day'),
            'class': 'span2',

        })
    )

    year = forms.CharField(
        label = _('Year'),
        min_length = 4,
        max_length = 4,
        widget = forms.TextInput(attrs={
            'placeholder':_('Year'),
            'class': 'span2',
        })
    )

    gender = forms.ChoiceField(
        choices = GENDER_CHOICES,
    )
    
    # gender = forms.CharField(label=_('Gender'))
    mobile = forms.CharField(
        label = _('Mobile'),
        min_length = 7,
        max_length = 20,
        widget = forms.TextInput(attrs={
            'placeholder':_('Mobile'),
        })
    )

    website = forms.CharField(
        label = _('Website'),
        min_length = 4,
        max_length = 100,
        widget = forms.TextInput(attrs={
            'placeholder':_('Website'),
        })
    )

class ChangePasswordForm(forms.Form):
    password = forms.CharField(
        label = _('Password'),
        min_length = 3,
        max_length = 30,
        widget = forms.PasswordInput(attrs={
            'placeholder':_('Password'),
        })
    )

    new_password = forms.CharField(
        label = _('New password'),
        min_length = 6,
        max_length = 30,
        widget = forms.PasswordInput(attrs={
            'placeholder':_('New password'),
        })
    )

    confirm_new_password = forms.CharField( # Why?!
        label = _('Re-type new password'),
        min_length = 6,
        max_length = 30,
        widget = forms.PasswordInput(attrs={
            'placeholder':_('Re-type new password'),
        })
    )

    def clean_confirm_new_password(self):
        confirm_new_password = self.cleaned_data['confirm_new_password']
        if confirm_new_password != self.cleaned_data['new_password']:
            raise forms.ValidationError(_('New password and Re-type does not match'))
        return confirm_new_password

class RegisterForm(forms.Form):
    error_messages = {
        'duplicate_username': _("A user with that username already exists."),
        'password_mismatch': _("The two password fields didn't match."),
    }
    # username = forms.RegexField(label=_("Username"), max_length=30,
    #     regex=r'^[\w.@+-]+$',
    #     help_text=_("Required. 30 characters or fewer. Letters, digits and "
    #                   "@/./+/-/_ only."),
    #     error_messages={
    #         'invalid': _("This value may contain only letters, numbers and "
    #                      "@/./+/-/_ characters.")},
    #     widget=forms.TextInput(attrs={
    #         'placeholder': _('Username'),
    #         'class': 'span12 required',
    #         'required': '',
    #     }))

    first_name = forms.CharField(
        label = _('First Name'), 
        min_length = 2, 
        max_length = 30,
        widget = forms.TextInput(attrs={
            'placeholder':_('First Name'),
            'class': 'span6 required',
            'required': '',
        })
    )

    last_name = forms.CharField(
        label = _('Last Name'),
        min_length = 2,
        max_length = 30,
        widget = forms.TextInput(attrs={
            'placeholder':_('Last Name'),
            'class': 'span6 required',
            'required': '',
        })
    )
    email = forms.EmailField(
        label = _('E-Mail'),
        min_length = 5,
        widget = forms.TextInput(attrs={
            'placeholder': _('Your email address'),
            'type': 'email',
            'class': 'span12 required',
            'required': '',
        })
    )
    password = forms.CharField(
        label = _('Password'),
        min_length = 6,
        max_length = 30,
        widget = forms.PasswordInput(attrs={
            'placeholder':_('Password'),
            'class': 'span6 required',
            'required': '',
        })
    )
    confirm_password = forms.CharField(
        label = _('Re-type password'),
        min_length = 6,
        max_length = 30,
        widget = forms.PasswordInput(attrs={
            'placeholder':_('Re-type password'),
            'class': 'span6',
            'required': '',
        })
    )

    gender = forms.ChoiceField(choices=GENDER_CHOICES)

    month = forms.ChoiceField(choices=MONTH_CHOICES,
        widget=forms.Select(attrs={
            'class': 'span4',
        })
    )

    day = forms.CharField(
        label = _('Day'),
        min_length = 1,
        max_length = 2,
        widget = forms.TextInput(attrs={
            'placeholder':_('Day'),
            'class': 'span4',
            'required': '',
        })
    )

    year = forms.CharField(
        label = _('Year'),
        min_length = 4,
        max_length = 4,
        widget = forms.TextInput(attrs={
            'placeholder':_('Year'),
            'class': 'span4',
            'required': '',
        })
    )

    def clean_day(self):
        day = int(self.cleaned_data['day'])
        if (day > 31 or day < 1):
            raise forms.ValidationError(_('Invalid date'))
        return day

    def clean_month(self):
        month = int(self.cleaned_data['month'])
        if (month > 12 or month < 1):
            raise forms.ValidationError(_('Invalid date'))
        return month

    def clean_year(self):
        year = int(self.cleaned_data['year'])
        if (year > 2012 or year < 1900):
            raise forms.ValidationError(_('Invalid date'))
        return year

    def clean_email(self):
        email = self.cleaned_data['email']
        from django.contrib.auth.models import User
        try:
            user = User.objects.get(email=email) 
        except User.DoesNotExist:
            return email
        else:
            # E-mail is a uniqe field 
            raise forms.ValidationError(_('You are member! Did you forget your password?'))

    def clean_password(self):
        password = self.cleaned_data['password']
        # Check strog password
        return password

    def clean_confirm_password(self):
        confirm_password = self.cleaned_data['confirm_password']
        if confirm_password != self.cleaned_data['password']:
            raise forms.ValidationError(_('Password and Re-type does not match'))
        return confirm_password

class NewPostForm(forms.Form):
    text = forms.CharField(
        label=_('Text'),
        widget=forms.Textarea(attrs={
            'placeholder': _('Say it!'),
            'rows': 3,
            'class': 'span12',
            'style': 'resize: none;',
        })
    )
    book = forms.CharField(
        label=_('Book'),
        widget=forms.TextInput(attrs={
            'placeholder': _('Book Name'),
            'autocomplete': 'off',
            'data-provide': 'typeahead',
            'class': 'span6 typeahead',
            'id': 'title-look',
        })
    )    
    author = forms.CharField(
        label=_('Author'),
        widget=forms.TextInput(attrs={
            'placeholder': _('Author Name'),
            'autocomplete': 'off',
            'data-provide': 'typeahead',
            'class': 'span6 typeahead',
            'id': 'author-look',
        })
    )

darkoob/social/templates/social/home.html
{% extends "base/profile_base.html" %}

{% load avatar_tags %}
{% load staticfiles %}
{% load endless %}
{% load thumbnail %}
{% load kwacros %}

{% loadkwacros "base/macros.html" %}

{% block css %}
{{ block.super }}
<link rel="stylesheet" type="text/less" href="{% static "/static/css/home_style.less" %}">
{% endblock css %}

{% block js %}
{{ block.super }}
{% endblock js %}

{% block sidebar %}
<div class="row-fluid">
  <div class="span12">
    <script type="text/javascript">
      //TODO: It's very dirty code
      function close_1(){
        $('#follow_suggestion_1').remove();
      }
      function close_2(){
        $('#follow_suggestion_2').remove();
      }
      function close_3(){
        $('#follow_suggestion_3').remove();
      }
      function follow_request_callback_1(data){
        alert(data.done);
        close_1();
      }
      function follow_request_callback_2(data){
        alert(data.done);
        close_2();
      }
      function follow_request_callback_3(data){
        alert(data.done);
        close_3();
      }
    </script>
        <ul class="nav nav-tabs nav-stacked left-nav">
          <li class="li-home">
            <a data-pjax href="{% url 'social:home_stream' %}">
              <i class="icon-home"></i> Home<i class="icon-chevron-right pull-right"></i>
            </a>
          </li>
          <li class="li-profile">
            <a data-pjax href="{% url 'social:profile' %}">
              <i class="icon-user"></i> Profile<i class="icon-chevron-right pull-right"></i>
            </a>
          </li>
          <li class="li-followers">
            <a data-pjax href="{% url 'social:followers' %}">
              <i class="icon-eye-open"></i> Followers <i class="icon-chevron-right pull-right"></i>
            </a>
          </li>
          <li class="li-following">
            <a data-pjax href="{% url 'social:following' %}">
              <i class="icon-heart"></i> Following <i class="icon-chevron-right pull-right"></i>
            </a>
          </li>
          <li class="li-fav-books">
            <a data-pjax href="{% url 'social:favorite_books' %}">
              <i class="icon-star"></i> Favorite Books <i class="icon-chevron-right pull-right"></i>
            </a>
          </li>
        </ul>

    <div class="row-fluid">
      <h4 class="sidebox-head">DO YOU KNOW. . .?</h4> 
      <div class="span12 simple_box">


        <!--# TODO : ISSUE #54-->
        <ul class="thumbnails span10 offset1">
          {% for suggestion in suggestion_list %}
            <div class="row-fluid">
              <li class="span3">
              {% usekwacro user_details user_=suggestion placement='top' %}
                <a href="{% url 'social:user_profile' username=suggestion %}" class="thumbnail">
                    {% avatar suggestion %}
                  </a>
              </div>
              </li>
              <div class="span9 suggestion-info">
                {% usekwacro user_details user_=suggestion placement='top' %}
                  <div class="username">
                    <a href="{% url 'social:user_profile' username=suggestion %}">{{ suggestion.get_full_name }}</a>
                  </div>
                </div> <!-- user-details -->
                <div class="small-info">
                  2 Mutual friends
                </div>
              </div>
            </div>
          {% empty %}
            <p>Sorry, we have no information about you to suggest other users regarding them!</p>
          {% endfor %}
        </ul>

          <!--
        <p id='person_box'>
          <div id='follow_suggestion_1'>
            <button class="close" id="close_button_1" onmousedown="close_1()">&times;</button>
            {{ suggestion_list.0 }} <a onmousedown="Dajaxice.darkoob.social.follow_request(follow_request_callback_1,{'following_id': {{suggestion_list.0.id }}})">Follow</a>
          </div>
          <div id='follow_suggestion_2' id="close_button_2" onmousedown="close_2()">
            <button class="close">&times;</button>
            {{ suggestion_list.1 }} <a onmousedown="Dajaxice.darkoob.social.follow_request(follow_request_callback_2,{'following_id': {{suggestion_list.1.id }}})">Follow</a>
          </div>
          <div id='follow_suggestion_3' id="close_button_3" onmousedown="close_3()">
            <button class="close">&times;</button>
            {{ suggestion_list.2 }} <a onmousedown="Dajaxice.darkoob.social.follow_request(follow_request_callback_3,{'following_id': {{suggestion_list.2.id }}})">Follow</a>
          </div>
          </p>-->
      </div> <!-- span12 -->
    </div> <!-- row -->

    <div class="row-fluid">

      <h4 class="sidebox-head">RECEIVED A BOOK?</h4>
      <div class="span12 simple_box hopping">
        <p>
          Did a book hop to you? Submit the private key here:
        <form class="form-inline" onsubmit="return false;">
          <input type="text" class="input-medium" placeholder="Private Key" autocomplete="off" data-toggle="tooltip" id='id_private_key' > 
      

          <button id='check_primary_key' data-toggle="button" data-loading-text="loading stuff..." class="btn btn-primary" data-complete-text="finished!" onclick="Dajaxice.darkoob.migration.submit_key(submit_private_key_callback,{'private_key': $('#id_private_key').val() })">Submit</button>
        </form>
        <em><a href="{% url 'migration:new_migration' %}">Start a new book migration</a></em>
<!--         <button class="btn btn-large btn-block btn-primary" type="button">Start New Migration</button> -->

        </p>
      </div> <!-- span10 -->
    </div> <!-- row -->

    {% usekwacro group_box admin_groups=admin_groups groups=groups first_name='' %}

    {% usekwacro deadline_box book_deadlines=book_deadlines %}

  </div> <!-- span12 -->
</div> <!-- row -->
{% endblock sidebar %}

{% block main %}
<div class="row-fluid">
  <div class="span11 offset1">
      <div class="row-fluid">
        <div class="span12">
          {% usekwacro top_quote quote_=quote %}
        </div> <!-- span12 -->
      </div> <!-- row -->
    <div id="pjax-container">
      {% block pjax_container %}
        <script type="text/javascript">
          $(document).ready(function() {
            $.pjax({url: "{% url 'social:home_stream' %}", container: '#pjax-container'});
          });
        </script>
      {% endblock pjax_container %}
    </div> <!-- pjax-container -->
  </div> <!-- span11 -->
</div> <!-- row -->
{% endblock main %}

{% block bottom_js %}
{{ block.super }}
<script type="text/javascript" src="{% static "/static/js/home.js" %}"></script>
{% endblock bottom_js %}

darkoob/social/templates/social/signup.html
chera ino nemishnase?

darkoob/social/templates/social/user_profile.html
{% extends "base/profile_base.html" %}

{% load staticfiles %}
{% load thumbnail %}
{% load avatar_tags %}
{% load kwacros %}
{% loadkwacros "base/macros.html" %}

{% block css %}
{{ block.super }}
<link rel="stylesheet" type="text/less" href="{% static "/static/css/profile_base_style.less" %}">
<link rel="stylesheet" type="text/less" href="{% static "/static/css/home_style.less" %}">
{% endblock css %}

{% block js %}
{{ block.super }}
{% endblock js %}

{% block title %}Darkoob - {{ person_object.get_full_name }} page{% endblock title %}


{% block sidebar %}
<div class="row-fluid">
  <div class="span12">
    <div class="media">
      <a class="pull-left" href="#">
        {% avatar person_object 100 %}          
      </a>
      <div class="media-body">
        <h4 class="media-heading"><a href="{% url 'social:user_profile' username=user.username %}">
        {{person_object.first_name|capfirst}} {{person_object.last_name|capfirst}}</a></h4>
        {{ person_object.userprofile.gender }}<br />
        {{ person_object.userprofile.birthday }}<br />
        It is {% now "c" %} 

        {% if person_object.userprofile.city %}{{ person_object.userprofile.city|capfirst }}/{{person_object.userprofile.city.country|capfirst}}{% endif %}
      </div>

    </div>
    <br/>
    {%if person_object.userprofile.mobile %}
    <b>Mobile</b> {{person_object.userprofile.mobile}}
    {% endif%}

    {% if person_object.userprofile.website %}
    <address>
      <b>Webpage</b> <a href="{{person_object.userprofile.website}}">{{person_object.userprofile.website|truncatechars:35}}</a>
    </address>
    {% endif%}


    {% if is_followers %}
      <i class="icon-eye-open"></i>
      {{person_object.first_name|capfirst}} is following you <br/>
    {% endif %}

    {% if is_following %}
      <button class="btn btn-small btn-block disabled" disabled="disabled" onclick="Dajaxice.darkoob.social.follow_person(follow_person_callback, {'user_id': {{person_object.id}}})"><i class="icon-eye-open"></i> You are following {{person_object.first_name|capfirst}}
      </button>

    {% else %}
      <script type="text/javascript">
        function follow_person_callback(data){
          if(data.done){
            $.pnotify({
              title: 'Following',
              text: 'You follow {{person_object.get_full_name}} ',
              type: 'success',
              opacity: .8,
            });
            $('#follow_btn').attr('disabled', 'disabled');
            $('#follow_btn').attr('class', 'btn btn-small btn-block disabled');
          }else{
            $.pnotify({
              title: 'Following',
              text: 'An error occured, Try again',
              type: 'error',
              opacity: .8,
            });
          }
        }
      </script>
      <button id="follow_btn" class="btn btn-small btn-block" onclick="Dajaxice.darkoob.social.follow_person(follow_person_callback, {'user_id': {{person_object.id}}})"><i class="icon-eye-close"></i> Follow {{person_object.first_name|capfirst}}</button>
    {% endif %}
    
  
    <br/>

    <ul class="nav nav-tabs nav-stacked">
        {% block followers_active %}
        <li>
        <a href="{% url 'social:user_followers' username=person_object.username %}" ><i class="icon-eye-open"></i> Followers
          <i class="icon-chevron-right" style="float:right"></i></a>
        </li>
        {% endblock followers_active%}
        {% block following_active %}
        <li>
          <a href="{% url 'social:user_following' username=person_object.username %}"><i class="icon-heart"></i> Following <i class="icon-chevron-right" style="float:right"></i></a>
        </li>
        {% endblock following_active%}
        {% block favorite_book_active %}
        <li>
          <a href="{% url 'social:user_favorite_books' username=person_object.username %}"><i class="icon-star"></i> Favorite Books <i class="icon-chevron-right" style="float:right"></i></a>
        </li>
        {% endblock favorite_book_active %}

      </ul>
      
      {% usekwacro group_box admin_groups=admin_groups groups=groups first_name=person_object.first_name %}

    </div> <!-- span12 -->
  </div> <!-- row -->
  {% endblock sidebar %}

  {% block main %}


  <div class="row-fluid">
    <div class="span11 offset1">
      <div class="row-fluid">
        <div class="span12">
          {% usekwacro top_quote quote_=person_object.userprofile.quote %}
          {% if not person_object.userprofile.quote %}
            <script type="text/javascript">
              Dajaxice.darkoob.social.get_quote(Dajax.process);
            </script>
          {% endif %}
        </div>
      </div>

      {% block right_sidebox %}

      <div class="sidebox-head" style="margin-left: 0;">
        <h4>Migrations</h4>
      </div>
      <div class="span12 simple_box" style="margin-left: 0;">


        <p>
          <div class="migrations" style="display: block;">
            <div class="row-fluid">
              <div>
                {% for migration in migrations %}
                  <div class="migration">

                    <div class="migration-book">
                      <a style="Display:none">{{ migration.book.title }}</a>
                      {% thumbnail migration.book.thumb "50x50" crop="center" as im %}
                        <img rel="tooltip" title="d" src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
                      {% endthumbnail %}
                    </div> <!-- migration-book -->

                    <div class="offset1" style="display: inline-block;">
                      <div class="migration-hop" style="display: inline-block;">
                        <a style="Display:none">{{ migration.starter.get_full_name }}</a>
                        {% avatar migration.starter 30%}
                      </div>

                      {% for hop in migration.hop_set.all|slice:":"|dictsort:"received_time" %}
                        <i class="icon-chevron-right"></i>
                        <div class="migration-hop" style="display: inline-block;">
                          <a style="Display:none">{{ hop.host.get_full_name }}</a>
                          {% avatar hop.host 30 %}
                        </div>
                      {% endfor %}
                    </div>

                  </div> <!-- migration -->
                {% endfor %}

                <script type="text/javascript">

                $('.migration-book, .migration-hop').each(function(){

                  $($(this).children()[1]).removeAttr('data-original-title')
                  $($(this).children()[1]).attr('title',$(this).children()[0].text)
                  $($(this).children()[1]).tooltip({
                    'placement': 'bottom'
                  });
                });

                </script>
              </div>
            </div> <!-- row -->
          </div> <!-- migrations -->
        </p>

      </div>



      <div class="row-fluid">
        <div class="span12">
          {% include 'post/posts.html' %}
        </div>
      </div>

      <div class="row-fluid">
        <div class="span12">


        </div> <!-- span12 -->
      </div> <!-- row -->

      {% endblock right_sidebox %}




    </div> <!-- span12 -->
  </div> <!-- row -->
  {% endblock main %}