darkoob/book/urls.py
from django.conf.urls import patterns, include, url
from darkoob.book import views as book_views

urlpatterns = patterns('',
    url(r'^(?P<book_id>\d+)/(?P<book_title>[a-zA-Z0-9\-_]+)/$', book_views.page, name='book_page'),
    url(r'^look/$', book_views.book_lookup),
    url(r'^author/$', book_views.author_lookup),
    # url(r'^rate/$', book_views.rate, name='rate'),
)

darkoob/social/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.auth import views as auth_views

from darkoob.social import views as social_views
from darkoob.social.forms import AuthenticationFormPlaceholder

urlpatterns = patterns('',
    url(r'^home/$', social_views.home, name='home'),
    url(r'^home/stream/$', social_views.home_stream, name='home_stream'),
    url(r'^signup/$', social_views.signup, name='signup'),
    url(r'^login/$', auth_views.login,
        {'template_name': 'social/login.html',
         'authentication_form': AuthenticationFormPlaceholder
        }, name='login'),
    url(r'^logout/$', auth_views.logout_then_login, name='logout'),
    url(r'^change_password/$', social_views.change_password, name='change_password'),
    url(r'^profile/$', social_views.profile, name='profile'),

    url(r'^password/reset/$', auth_views.password_reset, 
        {'post_reset_redirect': 'password/reset/done/'}, name='reset_pass'),
    url(r'^password/reset/done/$', auth_views.password_reset_done),
    url(r'^password/reset/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$', auth_views.password_reset_confirm, 
        {'post_reset_redirect': 'password/done/'}),
    url(r'^password/done/$', auth_views.password_reset_complete),

    url(r'^post/new/$', social_views.new_post, name='new_post'),
    url(r'^user/(?P<username>\w+)/$', social_views.user_profile, name='user_profile'),

    url(r'^user/(?P<username>\w+)/following$', social_views.user_following, name='user_following'),
    url(r'^user/(?P<username>\w+)/followers$', social_views.user_followers, name='user_followers'),
    url(r'^user/(?P<username>\w+)/favorite_books$', social_views.user_favorite_books, name='user_favorite_books'),

    url(r'^profile/followers/$', social_views.followers, name='followers'),
    url(r'^profile/following/$', social_views.following, name='following'),
    url(r'^profile/favorite_books$', social_views.favorite_books, name='favorite_books'),
)

darkoob/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from dajaxice.core import dajaxice_autodiscover, dajaxice_config

from darkoob import views 
from darkoob import ajax 


dajaxice_autodiscover()
admin.autodiscover()

urlpatterns = patterns('',
    # search url
    url(r'^search/', include('haystack.urls')),
    # Django Admin
    url(r'^admin/', include(admin.site.urls)),

    # Static URL
    url(r'', include('django.contrib.staticfiles.urls')),

    # Dajaxice URLs 
    url(r'^ajaxice', views.index),
    url(dajaxice_config.dajaxice_url, include('dajaxice.urls')),

    # Project-specific URLs
    url(r'^$', views.index, name='index'),
    url(r'', include('darkoob.social.urls', namespace='social', app_name='socials')),
    url(r'', include('darkoob.migration.urls', namespace='migration')),

    url(r'^book/', include('darkoob.book.urls', namespace='book')),
    url(r'^group/', include('darkoob.group.urls', namespace='group')),
    # Search 
    # TODO: Move to search application
    url(r'', include('darkoob.search.urls', namespace='search')),

    # url(r'^comments/', include('django.contrib.comments.urls')),

    url(r'^avatar/', include('avatar.urls')),
)

from django.conf import settings
media_root = getattr(settings, 'MEDIA_ROOT', '/media')    

urlpatterns += patterns('', 
url(r'^media/(?P<path>.*)$','django.views.static.serve',
    {'document_root': media_root})
)

darkoob/book/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from taggit.managers import TaggableManager
from djangoratings.fields import RatingField
from sorl.thumbnail import ImageField

def first_user():
    return User.objects.get(pk=1)

class Book(models.Model):
    title = models.CharField(max_length=255, db_index=True)
    publisher = models.ForeignKey('Publisher',null=True, blank=True)
    language = models.ForeignKey('Language', null=True, blank=True)
    authors = models.ManyToManyField('Author')
    tags = TaggableManager(blank=True)
    pages = models.IntegerField(blank=True, null=True)
    thumb =  models.ImageField(upload_to='books/', default='books/default.jpg')
    rating = RatingField(range=5, can_change_vote=True, allow_delete=False, allow_anonymous=False)
    creation_time = models.DateTimeField(default=timezone.now())
    user = models.ForeignKey(User, default=first_user)
    
    def author_names(self):
        return ', '.join([a.name for a in self.authors.all()])
    author_names.short_description = "Author Names"

    def __unicode__(self):
        return unicode(self.title)

class Publisher(models.Model):
    name = models.CharField(max_length=255)

    def __unicode__(self):
        return unicode(self.name)

class Language(models.Model):
    name = models.CharField(max_length=255)

    def __unicode__(self):
        return unicode(self.name)

class Author(models.Model):
    name = models.CharField(max_length=255)

    def __unicode__(self):
        return unicode(self.name)

class Translator(models.Model):
    author = models.OneToOneField(Author)

    def __unicode__(self):
        return unicode(self.author)

class Translation(models.Model):
    book = models.ForeignKey(Book)
    translator = models.ForeignKey(Translator)
    language = models.ForeignKey(Language)

    def __unicode__(self):
        return unicode(self.book)

class Review(models.Model):
    book = models.ForeignKey(Book, db_index=True)
    user = models.ForeignKey(User)
    title = models.TextField()
    text = models.TextField()
    submitted_time = models.DateTimeField(default=timezone.now(), db_index=True)
    rating = RatingField(range=5, can_change_vote=True, allow_delete=False, allow_anonymous=False)

    def __unicode__(self):
        return unicode(self.book) + unicode(self.user)

class Quote(models.Model):
    author = models.ForeignKey(Author, null=True, blank=True)
    book = models.ForeignKey(Book, null=True, blank=True)
    user = models.ForeignKey(User, null=True, blank=True, db_index=True)
    submitted_time = models.DateTimeField(default=timezone.now(), db_index=True)
    text = models.TextField()

    @classmethod
    def get_random_quote(cls):
        try:
            quote = cls.objects.order_by('?')[0]
        except Exception, e:
            print e
            author= Author.objects.create(name='Albert Einstein')
            u = User.objects.get(pk=1)
            quote = Quote.objects.create(
                author=author,
                user=u,
                text="Two things are infinite: the universe and human stupidity\
                ; and I'm not sure about the universe."
            )

        return quote

    def __unicode__(self):
        return unicode(self.text)

darkoob/migration/models.py
from django.db import models
from django.contrib.auth.models import User
from darkoob.book.models import Book

class Hop(models.Model):
    migration = models.ForeignKey('Migration')
    host = models.ForeignKey(User, related_name='host_set', db_index=True)
    received_time = models.DateTimeField(auto_now_add=True, db_index=True)

    class Meta:
        unique_together = (("migration", "host"),)

    def __unicode__(self):
        return unicode("%s - %s" % (self.migration, self.host.username))

class Migration(models.Model):
    book = models.ForeignKey(Book, related_name='book_set')
    starter = models.ForeignKey(User, related_name='starter_set')
    starter_message = models.TextField()
    start_time = models.DateTimeField(auto_now_add=True, db_index=True)
    private_key = models.CharField(max_length=10, unique=True)
 
    def get_user_hoped_migrations(self, user):
        '''return all migration's objects that hoped in user'''
        return [hop.migration for hop in Hop.objects.filter(host=user)]

    def get_user_host_migrations(self, user):
        '''return all migration's objects that hosted by user'''
        return [migrate for migrate in Migration.objects.filter(starter=user)]

    def get_user_related_migrations(self, user):
        '''return get_user_host_migrations() +  get_user_hoped_migrations()'''
        return self.get_user_hoped_migrations(user) + self.get_user_host_migrations(user)

    def __unicode__(self):
        return unicode("%s - %s" % (self.book.title, self.starter.username))

darkoob/book/forms.py
from django import forms
from django.utils.translation import ugettext as _

class NewReviewForm(forms.Form):
    text = forms.CharField(
        label=_('Text'),
        widget=forms.Textarea(attrs={
            'placeholder': _('Write Your Review about this book.'),
            'rows': 3,
            'class': 'span12',
            'style': 'resize: none;',
        })
    )
    title = forms.CharField(
        label=_('Book'),
        widget=forms.TextInput(attrs={
            'placeholder': _('Title of Review'),
            'autocomplete': 'off',
            'class': 'span10',
        })
    )    

darkoob/book/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, render_to_response
from django.core.urlresolvers import reverse
from django.http import Http404
from django.utils.translation import ugettext as _
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.template import RequestContext
from django.db import transaction
from django.utils import simplejson

from darkoob.book.models import Book, Author
from darkoob.book.forms import NewReviewForm
from darkoob.social.views import common_context
from darkoob.migration.models import Migration


from darkoob.book.models import Review

def page(request, book_id, book_title):
    try:
        book = Book.objects.get(id=book_id)
    except Book.DoesNotExist:
        raise Http404
    template = 'book/book_page.html'
    reviews = Review.objects.filter(book=book).order_by("-rating_score")
    count = range(1, len(reviews) + 1)
    if request.is_ajax():
        template = 'book/reviews.html'

    context = {
        'new_review_form': NewReviewForm(),
        'book': book,
        'rate': book.rating.get_rating(),
        'reviews': reviews,
        'count': count[::-1],
        'migrations': Migration.objects.filter(book=book),
    }
    common_context(request, context)
    m = Migration() 

    return render(request, template, context)


from avatar.templatetags import avatar_tags


def book_lookup(request):
    results = []
    if request.method == "GET":
        if request.GET.has_key(u'query'):
            value = request.GET[u'query']
            model_results = Book.objects.filter(title__icontains=value)
            results = [ {'book_title': x.title ,'book_id':x.id ,'photo': x.thumb.url , 'author_name': x.author_names() }  for x in model_results]

    to_json = []

    jt = simplejson.dumps(results)
    print jt
    return HttpResponse(jt, mimetype='application/json')

def author_lookup(request):
    results = []
    if request.method == "GET":
        if request.GET.has_key(u'query'):
            value = request.GET[u'query']
            model_results = Author.objects.filter(name__icontains=value)
            results = [ x.name for x in model_results]

    to_json = []

    jt = simplejson.dumps(results)
    print jt
    return HttpResponse(jt, mimetype='application/json')
    

darkoob/book/templates/book/book_page.html
{% extends "social/home.html" %}
{% load staticfiles %}
{% load thumbnail %}
{% block css %}
{% load avatar_tags %}

{{ block.super }}
<link rel="stylesheet" type="text/less" href="{% static "/static/css/profile_base_style.less" %}">
<link rel="stylesheet" type="text/less" href="{% static "/static/css/home_style.less" %}">
{% endblock css %}

{% block title %}Darkoob - {{ book.title }}{% endblock title %}

{% block main %}
<div class="row-fluid">
  <div class="span12">

    <div class="row-fluid">
      <div class="span12 sidebox">
        <div class="row-fluid" style="margin:10px">

          <div class="span2" >
            <div class="thumb">
              {% thumbnail book.thumb "170x220" crop="center" as im %}
              <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
              {% endthumbnail %}  
            </div> <!-- thumb -->
          </div> <!-- span2 -->
          <div class="span10">
            <div class="row-fluid">
              <div class="span8">
                <h4>{{ book.title|capfirst }}</h4>
              </div><!-- span8 -->
              <div class="span4">
                <div id="star" style="margin-top:10px"></div>  
                  <!-- javascript code for raty -->     
                  <script type="text/javascript" src="{% static "/static/js/jquery.raty.min.js" %}"></script>
                  <script type="text/javascript">
                    function rate_book_callback(data){
                      if (data.done){
                       $.pnotify({
                        title: 'Book Rating',
                        text: 'Your rate to this Book recorded',
                        type:'success',
                        opacity: .8
                      })
                     }
                    }
                    $(function(){
                      $.fn.raty.defaults.path='/static/img';
                      $('#star').raty({
                        score: {{ rate }},
                        click: function(score, evt) {
                          Dajaxice.darkoob.book.rate(rate_book_callback,{'rate':score , 'book_id':{{ book.id }} });
                        }
                      });
                    });
                  </script>
                  <!-- javascript code for raty -->
              </div><!-- span4 -->
            </div><!-- row-fluid -->
              <b>Author(s):</b>
              {% for author in book.authors.all %}
                {{ author.name|capfirst }}{% if not forloop.last %}, {% endif %}
              {% endfor %}<br/>
              <b>Publisher:</b>
              {% if book.publisher %}
                {{ book.publisher.name}}
              {% endif %}
          </div><!-- span10 -->
        </div><!-- row-fluid -->

        <div class="row-fluid" style="margin:10px">
          <div class="span10">
              <i class="icon-tags"></i>
            <b>Tags:</b>
            {% for tag in book.tags.all %}
              {{ tag|lower }}{% if not forloop.last %}, {% endif %}
            {%endfor %}
          </div><!-- span10 -->
          <div class="span2">
            {% if book in request.user.userprofile.favorite_books.all %}
              <button class="btn btn-success btn-primary disabled" disabled="disabled" href="#" style="float:left"><i class="icon-star"></i></button>
            {% else %}
              <button class="btn btn-success btn-primary" href="#" style="float:left"><i class="icon-star"></i></button>
            {% endif %}
          </div><!-- span2 -->
        </div> <!-- row-fluid -->

      </div> <!-- span12 sidebox -->
    </div> <!-- row -->


    <h4 class="migrations-link migrations-link-inactive pull-right"><i class="icon-chevron-left"></i>MIGRATIONS</h4>
      <div class="migrations">
        <div class="row-fluid">
          <div class="span12 sidebox">
            <div>
              {% for migration in migrations %}
                <div class="migration">



                  <div style="display: inline-block;">
                    <div class="migration-hop" style="display: inline-block;">
                      <a style="Display:none">{{ migration.starter.get_full_name }}</a>
                      {% avatar migration.starter 30%}
                    </div>

                    {% for hop in migration.hop_set.all|slice:":"|dictsort:"received_time" %}
                      <i class="icon-chevron-right"></i>
                      <div class="migration-hop" style="display: inline-block;">
                        <a style="Display:none">{{ hop.host.get_full_name }}</a>
                        {% avatar hop.host 30 %}
                      </div>
                    {% endfor %}
                  </div>

                </div> <!-- migration -->
              {% endfor %}

              <script type="text/javascript">         

              $('.migration-book, .migration-hop').each(function(){

                $($(this).children()[1]).removeAttr('data-original-title')
                $($(this).children()[1]).attr('title',$(this).children()[0].text)
                $($(this).children()[1]).tooltip({
                  'placement': 'bottom'
                });
              });

            </script>
          </div>
        </div> <!-- span12 -->
      </div> <!-- row -->
    </div> <!-- migrations -->




    <h4 class="sidebox-head">WRITE A REVIEW</h4>
    <div class="row-fluid">
      <div class="span12">
        <div class="sidebox">
          <div class="row-fluid">
            <div class="span9 new_post_container">              

              <form method="post" action="" id="post_form" type='0'>
                {{ new_review_form.text }}
                {{ new_review_form.title }}
              </form>
            </div>
            <div class="span1 new_post_button">
              <button id="post_button" class="btn btn-inverse" onclick="Dajaxice.darkoob.book.submit_review(Dajax.process, {'book_id':{{ book.id }}, 'text': $('#id_text').val(), 'title': $('#id_title').val()})">Post</button>
            </div>
          </div> <!-- row -->
        </div> <!-- sidebox -->
      </div> <!-- span11 -->
    </div> <!-- row-fluid -->


    <h4 class="sidebox-head">REVIEWS</h4>
    <div id="id_new_post_position">
    </div>
    {% include 'book/reviews.html' %}

  </div> <!-- span12 -->
</div> <!-- row-fluid -->
{% endblock main %}

darkoob/book/templates/book/review.html
{% load avatar_tags %}
{% load staticfiles %}

{% load kwacros %}
{% loadkwacros "base/macros.html" %}

<div class="row-fluid" id="id_post_id_{{ review.id }}">
  <div class="span12">
    <div class="sidebox post">
      <div class="row-fluid">
        <div class="span6">
          <div class="post-head">
            <div class="row-fluid">
              {% usekwacro user_details user_=review.user placement='top' %}
              <a href="{% url 'social:user_profile' username=review.user.username %}">
                <div class="avatar pull-left">
                  {% avatar review.user %}
                </div>
              </a>
            </div> <!-- user-details -->
            <div class="post-head-box">
              {% usekwacro user_details user_=review.user placement='top' %}
              <div class="username">
                <a href="{% url 'social:user_profile' username=review.user.username %}"><strong>{{ review.user.first_name }} {{review.user.last_name }}</strong></a>
              </div>
            </div> <!-- user-details -->
            <div class="row-fluid">
              <div class="small-info">
                <small>{{ review.submitted_time|timesince }}</small>
              </div>

            </div> <!-- row -->
          </div> <!-- post-head-box -->

        </div> <!-- row -->
      </div> <!-- post-head -->
    </div> <!-- span6 -->
  </div> <!-- row -->
  <div class="row-fluid">
    <div class="span12">
      <hr/>
      <div class="row" style="margin-left:20px">
        <div class="span8">
          <b>{{ review.title }}</b>
        </div>
        <div class="span4">
          <div class="star" style="float:right" review_id={{ review.id }} current_rate={{ review.rating.get_rating }}></div>
        </div>
      </div>
      <div class="post_content">
        <div class="row-fluid">
          {{ review.text }}
        </div> <!-- post_content -->
      </div> <!-- span12 -->
    </div> <!-- row -->
  </div> <!-- sidebox post -->
</div> <!-- span12 -->
</div> <!-- row -->






 

darkoob/book/templates/book/reviews.html
{% load endless %}

{% load staticfiles %}
{% paginate 1,1 reviews %}
  {% if not reviews %}
     <h5>Not found any review for this book. You can be the first!</h5>
  {% else%}
    {% for review in reviews %}
      {% include 'book/review.html' with review=review only %}
    {% endfor %}
  {% endif %}
<!-- javascript code for raty -->     
<script type="text/javascript" src="{% static "/static/js/jquery.raty.min.js" %}"></script>
<script type="text/javascript">
function review_callback(data){
  if (data.done){
    $.pnotify({
      title: 'Review Rating',
      text: 'Your rate to this review recorded',
      type:'success',
      opacity: .8
    })
  }
}
function load_starts(){
  $.fn.raty.defaults.path='/static/img';
  $('.star').each(function(){
    {
        $(this).raty({
        score: $(this).attr('current_rate'),
        click: function(score, evt) {
          Dajaxice.darkoob.book.review_rate(review_callback,
          {
            'rate':score, 
            'review_id': $(this).attr('review_id'), 
            });
          }
        });
    }
  })
};
load_starts();
</script>              
<!-- javascript code for raty -->

{% show_more "Get More" "Please Wait" %}