darkoob/book/urls.py
from django.conf.urls import patterns, include, url
from darkoob.book import views as book_views

urlpatterns = patterns('',
    url(r'^(?P<book_id>\d+)/(?P<book_title>[a-zA-Z0-9\-_]+)/$', book_views.page, name='book_page'),
    url(r'^look/$', book_views.book_lookup),
    url(r'^author/$', book_views.author_lookup),
    # url(r'^rate/$', book_views.rate, name='rate'),
)

darkoob/group/urls.py
from django.conf.urls import patterns, include, url
from darkoob.group import views as group_view
from darkoob.social import views as social_view

urlpatterns = patterns('',
    url(r'^(?P<group_id>\d+)/(?P<group_slug>[-\w]+)/$', group_view.group, name='group_page'),
    url(r'^new/$', group_view.create_group, name='create_group'),
    url(r'^look/$', social_view.user_lookup),
    url(r'^members/$', group_view.members, name='members'),
    url(r'^schedules/$', group_view.schedules, name='schedules'),
    url(r'^(?P<group_id>\d+)/(?P<group_slug>[-\w]+)/add-schedule/$', group_view.add_schedule, name='add_schedule'),
    # url(r'^rate/$', book_views.rate, name='rate'),

)

darkoob/search/urls.py
from django.conf.urls import patterns, include, url
from darkoob.search import views as search_views



urlpatterns = patterns('',
    url(r'^user/$', search_views.search_user),
    url(r'^users/$', search_views.search_user_result),
    url(r'^uu/$', search_views.entry_index),
    url(r'^uu1/$', search_views.entry_index1),
    url(r'^search/look/$', search_views.search_lookup),
)

darkoob/social/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.auth import views as auth_views

from darkoob.social import views as social_views
from darkoob.social.forms import AuthenticationFormPlaceholder

urlpatterns = patterns('',
    url(r'^home/$', social_views.home, name='home'),
    url(r'^home/stream/$', social_views.home_stream, name='home_stream'),
    url(r'^signup/$', social_views.signup, name='signup'),
    url(r'^login/$', auth_views.login,
        {'template_name': 'social/login.html',
         'authentication_form': AuthenticationFormPlaceholder
        }, name='login'),
    url(r'^logout/$', auth_views.logout_then_login, name='logout'),
    url(r'^change_password/$', social_views.change_password, name='change_password'),
    url(r'^profile/$', social_views.profile, name='profile'),

    url(r'^password/reset/$', auth_views.password_reset, 
        {'post_reset_redirect': 'password/reset/done/'}, name='reset_pass'),
    url(r'^password/reset/done/$', auth_views.password_reset_done),
    url(r'^password/reset/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$', auth_views.password_reset_confirm, 
        {'post_reset_redirect': 'password/done/'}),
    url(r'^password/done/$', auth_views.password_reset_complete),

    url(r'^post/new/$', social_views.new_post, name='new_post'),
    url(r'^user/(?P<username>\w+)/$', social_views.user_profile, name='user_profile'),

    url(r'^user/(?P<username>\w+)/following$', social_views.user_following, name='user_following'),
    url(r'^user/(?P<username>\w+)/followers$', social_views.user_followers, name='user_followers'),
    url(r'^user/(?P<username>\w+)/favorite_books$', social_views.user_favorite_books, name='user_favorite_books'),

    url(r'^profile/followers/$', social_views.followers, name='followers'),
    url(r'^profile/following/$', social_views.following, name='following'),
    url(r'^profile/favorite_books$', social_views.favorite_books, name='favorite_books'),
)

darkoob/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from dajaxice.core import dajaxice_autodiscover, dajaxice_config

from darkoob import views 
from darkoob import ajax 


dajaxice_autodiscover()
admin.autodiscover()

urlpatterns = patterns('',
    # search url
    url(r'^search/', include('haystack.urls')),
    # Django Admin
    url(r'^admin/', include(admin.site.urls)),

    # Static URL
    url(r'', include('django.contrib.staticfiles.urls')),

    # Dajaxice URLs 
    url(r'^ajaxice', views.index),
    url(dajaxice_config.dajaxice_url, include('dajaxice.urls')),

    # Project-specific URLs
    url(r'^$', views.index, name='index'),
    url(r'', include('darkoob.social.urls', namespace='social', app_name='socials')),
    url(r'', include('darkoob.migration.urls', namespace='migration')),

    url(r'^book/', include('darkoob.book.urls', namespace='book')),
    url(r'^group/', include('darkoob.group.urls', namespace='group')),
    # Search 
    # TODO: Move to search application
    url(r'', include('darkoob.search.urls', namespace='search')),

    # url(r'^comments/', include('django.contrib.comments.urls')),

    url(r'^avatar/', include('avatar.urls')),
)

from django.conf import settings
media_root = getattr(settings, 'MEDIA_ROOT', '/media')    

urlpatterns += patterns('', 
url(r'^media/(?P<path>.*)$','django.views.static.serve',
    {'document_root': media_root})
)

darkoob/book/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, render_to_response
from django.core.urlresolvers import reverse
from django.http import Http404
from django.utils.translation import ugettext as _
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.template import RequestContext
from django.db import transaction
from django.utils import simplejson

from darkoob.book.models import Book, Author
from darkoob.book.forms import NewReviewForm
from darkoob.social.views import common_context
from darkoob.migration.models import Migration


from darkoob.book.models import Review

def page(request, book_id, book_title):
    try:
        book = Book.objects.get(id=book_id)
    except Book.DoesNotExist:
        raise Http404
    template = 'book/book_page.html'
    reviews = Review.objects.filter(book=book).order_by("-rating_score")
    count = range(1, len(reviews) + 1)
    if request.is_ajax():
        template = 'book/reviews.html'

    context = {
        'new_review_form': NewReviewForm(),
        'book': book,
        'rate': book.rating.get_rating(),
        'reviews': reviews,
        'count': count[::-1],
        'migrations': Migration.objects.filter(book=book),
    }
    common_context(request, context)
    m = Migration() 

    return render(request, template, context)


from avatar.templatetags import avatar_tags


def book_lookup(request):
    results = []
    if request.method == "GET":
        if request.GET.has_key(u'query'):
            value = request.GET[u'query']
            model_results = Book.objects.filter(title__icontains=value)
            results = [ {'book_title': x.title ,'book_id':x.id ,'photo': x.thumb.url , 'author_name': x.author_names() }  for x in model_results]

    to_json = []

    jt = simplejson.dumps(results)
    print jt
    return HttpResponse(jt, mimetype='application/json')

def author_lookup(request):
    results = []
    if request.method == "GET":
        if request.GET.has_key(u'query'):
            value = request.GET[u'query']
            model_results = Author.objects.filter(name__icontains=value)
            results = [ x.name for x in model_results]

    to_json = []

    jt = simplejson.dumps(results)
    print jt
    return HttpResponse(jt, mimetype='application/json')
    

darkoob/group/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, render_to_response
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.utils.text import slugify
from django.utils import timezone
from django.template import RequestContext
from django.db import transaction

from darkoob.group.forms import GroupForm, NewScheduleForm
from darkoob.group.models import Group
from darkoob.book.models import Quote
from darkoob.social.forms import NewPostForm
from darkoob.group.models import Post

def group(request, group_id, group_slug):
    template = 'group/group_page.html'

    group = Group.objects.get(id=group_id)
    quote = Quote.get_random_quote()
    if request.is_ajax():
        template = 'post/posts.html'

    if group and group_slug == slugify(group.name):
        #group.admins = group.admin.admin_set.all()
        #group.members = group.members.all()

        is_member = False
        if group in request.user.group_set.all():
            is_member = True

        posts = Post.objects.filter(group=group).order_by("-submitted_time").all()

        # Calculate Deadlines for group
        book_deadlines = []
        for schedule in group.schedule_set.all():
            deadline_set = schedule.deadline_set.exclude(end_time__lte=timezone.now())
            for i in range(len(deadline_set)):
                deadline_set[i].time_percentage = (timezone.now() - deadline_set[i].start_time).total_seconds()  / (deadline_set[i].end_time - deadline_set[i].start_time).total_seconds() * 100
            if deadline_set:
                book_deadlines.append([ schedule.book , deadline_set])

        # Is this user admin of group?
        is_admin = False
        if request.user.id == group.admin.id:
            is_admin = True

        return render(request, template, {
            'group': group,
            'posts': posts,
            'quote': quote,
            'new_post_form': NewPostForm,
            'is_member': is_member,
            'is_admin': is_admin,
            'book_deadlines': book_deadlines,
            'schedule_form': NewScheduleForm(),
        })

    else:
        return HttpResponse("Group Is not exist!")

@login_required
def create_group(request):
    if request.method == 'POST':
        form = GroupForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            if not request.user.userprofile.quote:
                group = Group(name=cd['name'], admin=request.user)
            else:
                group = Group(name=cd['name'], admin=request.user, quote=request.user.userprofile.quote)
            group.save()
            for member in cd['members'].strip(',').split(','):
                try:
                    user = User.objects.get(username=member)
                    if user.id != request.user.id:
                        group.members.add(user)
                except:
                    pass
            group.save()
            groups = request.user.group_set.all()
            admin_groups = request.user.admin_set.all()
            return HttpResponseRedirect('/group/%i/%s'%(group.id,slugify(group.name)))

    else:
        form = GroupForm()
        groups = request.user.group_set.all()
        admin_groups = request.user.admin_set.all()
        return render(request, 'group/create_group.html', {'form': form, 'groups': groups, 'admin_groups': admin_groups })

@login_required
def members(request):
    pass

@login_required
def schedules(request):
    pass

@login_required
def add_schedule(request, group_id, group_slug):
    group = Group.objects.get(id=group_id)
    if group and group_slug == slugify(group.name):
        if request.method == 'POST':
            form = NewScheduleForm(request.POST)
            if group.admin.id == request.user.id:
                if form.is_valid():
                    cd = form.cleaned_data
                    book = Book.objects.get(name=cd['book'])
                    if book:
                        schedule = Schedule(group.id, book.id)
                        schedule.save()
                    groups = request.user.group_set.all()
                    admin_groups = request.user.admin_set.all()
                    return HttpResponseRedirect('/group/%i/%s'%(group.id,slugify(group.name)))
            else:
                pass
                # Permisson Denied
        else:
            if group.admin.id == request.user.id:
                form = NewScheduleForm()
                groups = request.user.group_set.all()
                admin_groups = request.user.admin_set.all()
                return render(request, '/group/add_schedule.html', {'form': form, 'groups': groups, 'admin_groups': admin_groups, 'group': group })
            else:
                pass
                #permisson denied

darkoob/migration/views.py
from django.utils.translation import ugettext as _
from django.http import HttpResponse
from darkoob.migration.forms import StartNewMigrationForm
from darkoob.book.models import Book
from darkoob.migration.models import Migration

import random
import string 
def generate_private_key(len=10):
    return ''.join(random.choice(string.ascii_uppercase + string.digits) for x in range(len))
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

@login_required
def start_new_migration(request):
    if request.method == 'POST':
        form = StartNewMigrationForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            try:
                book = Book.objects.get(title=cd['book'])
            except:
                return HttpResponse("this book no exist")
            else:
                private_key = generate_private_key()
                Migration.objects.create(book=book, starter=request.user,
                    starter_message=cd['starter_message'], private_key=private_key
                )
                # TODO:Redirect to this page 
                return render(request, 'migration/started.html', 
                    {'private_key': private_key, 'book': book}
                )
    else:
        form = StartNewMigrationForm()
    return render(request, 'migration/start_new_migration.html',{'form':form}) #{'form': form, })

darkoob/search/views.py
from django.shortcuts import render_to_response
from django.template.context import RequestContext
from django.db.models import Q
from django.contrib.auth.models import User
from django.utils import simplejson
from django.http import HttpResponse
from avatar.templatetags import avatar_tags
from itertools import chain
from darkoob.book.models import Book
# from haystack.query import SearchQuerySet
import re

def entry_index1( request ):
    return render_to_response('entry_index1.html', {}, context_instance = RequestContext(request))

def entry_index( request ):
    return render_to_response('entry_index.html', {}, context_instance = RequestContext(request))

def search_lookup(request):
    results = []
    if request.method == "GET":
        if request.GET.has_key(u'query'):
            value = request.GET[u'query']
            user_result = User.objects.filter(
                Q(first_name__icontains=value) |
                Q(last_name__icontains=value) |
                Q(username__icontains=value)
            )
            book_result = Book.objects.filter(
                Q(title__icontains=value) 
            )
            
            user_results = [{'username': x.username , 'photo': avatar_tags.avatar_url(x,30), 'full_name': x.get_full_name()}  for x in user_result ]
            book_results = [{'username': x.title , 'photo': x.thumb.url, 'full_name': x.author_names()}  for x in book_result ]
            # results = user_result + book_result
            results = list(chain(book_results,user_results))
            # help(SearchQuerySet())
            # res_obj = SearchQuerySet().autocomplete(userprofile_user_auto=value)
            # print res_obj
            # print SearchQuerySet().autocomplete(book_title_auto=value)
            # results = [{'username': x.username , 'photo': avatar_tags.avatar_url(x,30), 'full_name': x.get_full_name()}  for x in res_obj]
    to_json = []
    jt=simplejson.dumps(results)
    return HttpResponse(jt, mimetype='application/json')

def search_user( request ):
    return render_to_response('search_user.html', {}, context_instance = RequestContext(request))

def search_user_result( request ):
    query_string = ''
    found_entries = None
    if request.is_ajax():
        q = request.GET.get('q')
        if q is not None:            
            query_string = request.GET['q']
            print 'query_string:',query_string
            entry_query = get_query(query_string,['first_name','last_name','username'] )
            print 'entry_query:',entry_query
            results = User.objects.filter(entry_query)
            print "results", results
            return render_to_response(
                'search_user_result.html',
                {'results':results,}, 
                context_instance = RequestContext(request),
            )
    return render_to_response('search_user_result.html', {})


def normalize_query(query_string,
                    findterms=re.compile(r'"([^"]+)"|(\S+)').findall,
                    normspace=re.compile(r'\s{2,}').sub):
    """
    Splits the query string in invidual keywords, getting rid of unecessary spaces
    and grouping quoted words together.
    Example:
        >>> normalize_query('  some random  words "with   quotes  " and   spaces')
        ['some', 'random', 'words', 'with quotes', 'and', 'spaces']
    """
    return [normspace(' ', (t[0] or t[1]).strip()) for t in findterms(query_string)] 

def get_query(query_string, search_fields):
    ''' Returns a query, that is a combination of Q objects. That combination
    aims to search keywords within a model by testing the given search fields.
    '''
    query = None # Query to search for every search term        
    terms = normalize_query(query_string)
    for term in terms:
        or_query = None # Query to search for a given term in each field
        for field_name in search_fields:
            q = Q(**{"%s__icontains" % field_name: term})
            if or_query is None:
                or_query = q
            else:
                or_query = or_query | q
        if query is None:
            query = or_query
        else:
            query = query & or_query
    return query

darkoob/templates/base/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load dajaxice_templatetags %}
<html>
<head>
  <title>{% block title %}Darkoob{% endblock %}</title>

  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="content-type" content="text/html" charset=UTF-8">

  <link rel="stylesheet" type="text/less" href="{% static "/static/css/common_style.less" %}">
  <link rel="stylesheet" type="text/css" media="screen" href="{% static "/static/bootstrap/css/bootstrap.min.css" %}">
  <link rel="stylesheet" type="text/css" media="screen" href="{% static "/static/bootstrap/css/bootstrap-responsive.min.css" %}">
  <link rel="stylesheet" type="text/css" href="{% static "/static/css/jquery.pnotify.default.css" %}">
  <link rel="stylesheet" type="text/css" href="{% static "/static/css/jquery.pnotify.default.icons.css" %}">
  <link rel="stylesheet" type="text/css" href="{% static "/static/css/font.css" %}">
  {% block css %}
  {% endblock %}

  <script type="text/javascript" src="{% static "/static/js/jquery-1.10.2.min.js" %}"></script>
  <script type="text/javascript" src="{% static "/static/js/jquery.validate.min.js" %}"></script>
  <script type="text/javascript" src="{% static "/static/bootstrap/js/bootstrap.min.js" %}"></script>
  <script type="text/javascript" src="{% static "/static/dajax/jquery.dajax.core.js" %}"></script>
  <script type="text/javascript" src="{% static "/static/js/less-1.3.3.min.js" %}"></script>
  <script type="text/javascript" src="{% static "/static/js/jquery.pnotify.min.js" %}"></script>
  <script type="text/javascript" src="{% static "/static/js/base.js" %}"></script>

  {% dajaxice_js_import %}

  {% block js %}
  {% endblock %}


</head>
<body>
  {% block body %}
  {% endblock body %}
  <!--  <em>{% block footer %}کلیه حقوق این سایت متعلق به استاد حسن نادری می باشد! {% endblock %}</em> -->

{% block bottom_js %}
{% endblock bottom_js %}
</body>
</html>

darkoob/templates/base/macros.html
{% load avatar_tags %}
{% load kwacros %}

{% kwacro user_details user_=user placement='right' %}
  <div class="user" data-container="body" data-placement="{{ placement }}"
    data-content='
    <div class="user-details">
      <div class="row-fluid">
        <div class="span12">
          {% avatar user_ %}
        </div>
      </div>
      <div class="row-fluid">
        <div class="span12">
          <h4>{{ user_.get_full_name }}</h4>
          <small>@{{ user_.username }} &lt{{ user_.email }}&gt</small>
          <blockquote>
            {% if user_.userprofile.quote %}<em>{{ user_.userprofile.quote }}</em>{% endif %}
          </blockquote>
        </div>
      </div>
    </div>
    '>
{% endkwacro %}

{% kwacro top_quote quote_=quote %}
  <div id="top-quote">
    <blockquote quote-id="{{ quote_.id }}">
      <p id="quote-text">{{ quote_.text }}</p>
      <small id="quote-details">
        {{ quote_.author }}{% if quote_.book %} ({{ quote_.book }}){% endif %}
      </small>

      <i data-toggle="tooltip" class="icon-ok pull-right set-quote-icon"
        onclick="javascript:Dajaxice.darkoob.social.set_my_quote(
        set_my_quote_callback, {'quote_id': $('#top-quote blockquote').attr('quote-id') })">
      </i>
      <i data-toggle="tooltip" class="icon-circle-arrow-right pull-right next-quote-icon"
        onclick="Dajaxice.darkoob.social.get_quote(Dajax.process,{})">
      </i> 
    </blockquote>
  </div> <!-- top-quote -->

{% endkwacro %}

{% kwacro group_box admin_groups=admin_groups groups=groups first_name='' %}
  <div class="row-fluid">
    <h4 class="sidebox-head">GROUPS</h4>
    <div class="span12 simple_box groups">
      {% if not admin_groups|length == 0 %}
      <p>{% if first_name != '' %}{{ first_name }} is{% else %}You are{% endif %} the admin of</p>
      <ul>
        {% for group in admin_groups %}
        <li>
          <a href="{% url 'group:group_page' group_id=group.id group_slug=group.name|slugify %}"><i class="icon-th"></i> {{ group.name }}</a>
        </li>
        {% endfor %}
      </ul>
      {% endif %}
      {% if not groups|length == 0 %}
      <p>{% if first_name != '' %}{{ first_name }} is {% else %} You are {% endif %} a member of</p>
      <ul>
        {% for group in groups %}
        <li>
          <a href="{% url 'group:group_page' group_id=group.id group_slug=group.name|slugify %}"><i class="icon-th"></i> {{ group.name }}</a>
        </li>
        {% endfor %}
      </ul>
      {% endif %}
      <em><a href="{% url 'group:create_group' %}">create a new group</a></em>
    </div> <!-- span12 -->
  </div> <!-- row -->
{% endkwacro %}

{% kwacro simple_quote post_=post %}
  <!-- used in post.html -->
  <blockquote>
    <p id="quote_text">{{ post.text }}</p>
    <small>
      {{ post.author }}{% if post.book %} ({{ post.book }}){% endif %}
    </small>
    <i data-toggle="tooltip" id="set-quote-icon" class="icon-ok pull-right"
        onclick="javascript:Dajaxice.darkoob.social.set_my_quote(
      set_my_quote_callback, {'quote_id': {{ post.id}} })">
    </i>
  </blockquote>

{% endkwacro %}

{% kwacro deadline_box book_deadlines=book_deadlines is_admin=False %}
  
  {% if book_deadlines|length > 0 or is_admin %}
  <div class="row-fluid">
    <h4 class="sidebox-head">DEADLINES</h4>
    <div class="span12 simple_box deadlines">
      <div class="accordion" id="deadlines">
        {% for book in book_deadlines %}
        <div class="accordion-group">
          <div class="accordion-heading">
            <a class="accordion-toggle" data-toggle="collapse" data-parent="#deadlines" href="#deadline_details_{{ forloop.counter }}">
              <i class="icon-book"></i> {{ book.0 }}
            </a>
          </div>
          <div id="deadline_details_{{ forloop.counter }}" class="accordion-body collapse">
            <div class="accordion-inner">
              <ul style="margin-left: -1em;">
                {% for deadline in book.1 %}
                  <li style="display: block">
                    <div class="row-fluid">
                      <div class="span4 offset1">
                        <p style="float: left; display: inline-block; position: relative;">{{ deadline.from_page }} to {{ deadline.to_page }}</p>
                      </div>
                      <div class="span7">
                        <div class="progress 
                          {% if deadline.time_percentage > 90 %}progress-danger
                          {% elif deadline.time_percentage > 60 %}progress-warning
                          {% else %}progress-success{% endif %}">

                          <div class="bar" style="width: {% if deadline.time_percentage < 3 %} 3{% else %}{{ deadline.time_percentage }}{%endif%}%"></div>
                        </div>
                      </div>
                    </div>
                  </li>
                {% endfor %}
              </ul>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
      {% if is_admin %}
      <em><a href="{% url 'group:add_schedule' group_id=group.id group_slug=group.name|slugify %}">add new schedule</a></em>
      {% endif %}
    </div> <!-- span10 -->
  </div> <!-- row -->
  {% endif %}
{% endkwacro %}

darkoob/templates/base/pjax_base.html
{% block pjax_container %}
{% endblock pjax_container %}

{% block bottom_js %}
{% endblock bottom_js %}

darkoob/templates/base/profile_base.html
{% extends "base/base.html" %}
{% load staticfiles %}
{% load dajaxice_templatetags %}
{% load avatar_tags %}
{% load kwacros %}

{% kwacro user_details user placement='right' %}
  <div class="user" data-placement="{{ placement }}"
    data-content="<div class="row-fluid"><div class="span12">{% avatar user 64 %}</div></div>
                  <div class="row-fluid"><div class="span12">{{ user.get_full_name }}</div></div>">
{% endkwacro %}

{% block css %}
<link rel="stylesheet" type="text/less" href="{% static "/static/css/profile_base_style.less" %}">
<link rel="stylesheet" type="text/less" href="{% static "/static/css/posts_style.less" %}">
{% endblock css %}

{% block js %}
<script type="text/javascript" src="{% static "/static/js/jquery.pjax.js" %}"></script>
<script src="{% static "js/endless.js" %}" type="text/javascript" charset="utf-8" ></script>
<script src="{% static "js/endless_on_scroll.js" %}" type="text/javascript" charset="utf-8" ></script>
<script type="text/javascript" charset="utf-8" src="{% static "/static/js/holder.js" %}"></script>
<script type="text/javascript" charset="utf-8">
    var endless_on_scroll_margin = 1;
</script>
<script type="text/javascript" src="{% static '/static/js/post.js' %}"></script>
<script type="text/javascript" src="{% static '/static/js/profile_base.js' %}"></script>
<script type="text/javascript" src="{% static "/static/js/macros.js" %}"></script>
{% endblock js %}

{% block title %}Homepage{% endblock title %}

{% block body %}

<div class="container-fluid">
  <div class="row-fluid">
    <div class="span8 offset2">
      <div class="navbar">
        <div class="navbar-inner">
          <div class="container">
            <a class="brand pull-left" href="{% url "social:home" %}"><p class="logo">Darkoob</p></a>
            <form class="nav-search search_form pull-left">
              <ul class="nav">
                <li>
                <link rel="stylesheet" type="text/less" href="{% static "/static/css/typeahead_suggestion_with_photo_search.css" %}">
                <script src="{% static "/static/js/underscore.min.js" %}"></script>

                <input  
                type='text'
                class="typeahead search-query input-xlarge dropdown-toggle"
                autocomplete="off"
                placeholder="Search"
                id="search-look"
                data-provide="typeahead"
                >
                <script src="{% static "/static/js/search_typeahead_suggestion.js" %}"></script>

              <!--<ul id="search_results" class="dropdown-menu" role="menu" aria-labelledby="sLabel">
              </ul>-->
            </form>
            </li>
          </ul>
            <ul class="nav pull-right">
              <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" role="button" href="#">
                  {% avatar user 32 %}
                  <b class="caret"></b>
                </a>
                <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
                  <li><a href="{% url "social:profile" %}"><i class="icon-user"></i> Profile</a></li>
                  <li><a href="#"><i class="icon-wrench"></i> Settings</a></li>
                  <li><a href="{% url "social:logout" %}"><i class="icon-off"></i> Logout</a></li>
                </ul>
              </li> <!-- dropdown -->
            </ul> <!-- nav -->
          </div> <!-- container -->
        </div> <!-- navbar-inner -->
      </div> <!-- navbar -->
    </div> <!-- span -->
  </div> <!-- row -->
  <div class="row-fluid" id="structure">
    <div class="span12">
      <div class="row-fluid">
        <div class="span3 offset2">
          {% block sidebar %}
          {% endblock sidebar %}
        </div> <!-- span4 -->
        <div class="span5 " id="main">
          {% block main %}
          {%endblock main %}
        </div> <!-- span6 -->
      </div> <!-- row1 -->
    </div> <!-- span12 -->
  </div> <!-- row0 -->

</div> <!-- container -->
{% endblock body %}