darkoob/group/urls.py
from django.conf.urls import patterns, include, url
from darkoob.group import views as group_view
from darkoob.social import views as social_view

urlpatterns = patterns('',
    url(r'^(?P<group_id>\d+)/(?P<group_slug>[-\w]+)/$', group_view.group, name='group_page'),
    url(r'^new/$', group_view.create_group, name='create_group'),
    url(r'^look/$', social_view.user_lookup),
    url(r'^members/$', group_view.members, name='members'),
    url(r'^schedules/$', group_view.schedules, name='schedules'),
    url(r'^(?P<group_id>\d+)/(?P<group_slug>[-\w]+)/add-schedule/$', group_view.add_schedule, name='add_schedule'),
    # url(r'^rate/$', book_views.rate, name='rate'),

)

darkoob/social/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.auth import views as auth_views

from darkoob.social import views as social_views
from darkoob.social.forms import AuthenticationFormPlaceholder

urlpatterns = patterns('',
    url(r'^home/$', social_views.home, name='home'),
    url(r'^home/stream/$', social_views.home_stream, name='home_stream'),
    url(r'^signup/$', social_views.signup, name='signup'),
    url(r'^login/$', auth_views.login,
        {'template_name': 'social/login.html',
         'authentication_form': AuthenticationFormPlaceholder
        }, name='login'),
    url(r'^logout/$', auth_views.logout_then_login, name='logout'),
    url(r'^change_password/$', social_views.change_password, name='change_password'),
    url(r'^profile/$', social_views.profile, name='profile'),

    url(r'^password/reset/$', auth_views.password_reset, 
        {'post_reset_redirect': 'password/reset/done/'}, name='reset_pass'),
    url(r'^password/reset/done/$', auth_views.password_reset_done),
    url(r'^password/reset/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$', auth_views.password_reset_confirm, 
        {'post_reset_redirect': 'password/done/'}),
    url(r'^password/done/$', auth_views.password_reset_complete),

    url(r'^post/new/$', social_views.new_post, name='new_post'),
    url(r'^user/(?P<username>\w+)/$', social_views.user_profile, name='user_profile'),

    url(r'^user/(?P<username>\w+)/following$', social_views.user_following, name='user_following'),
    url(r'^user/(?P<username>\w+)/followers$', social_views.user_followers, name='user_followers'),
    url(r'^user/(?P<username>\w+)/favorite_books$', social_views.user_favorite_books, name='user_favorite_books'),

    url(r'^profile/followers/$', social_views.followers, name='followers'),
    url(r'^profile/following/$', social_views.following, name='following'),
    url(r'^profile/favorite_books$', social_views.favorite_books, name='favorite_books'),
)

darkoob/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from dajaxice.core import dajaxice_autodiscover, dajaxice_config

from darkoob import views 
from darkoob import ajax 


dajaxice_autodiscover()
admin.autodiscover()

urlpatterns = patterns('',
    # search url
    url(r'^search/', include('haystack.urls')),
    # Django Admin
    url(r'^admin/', include(admin.site.urls)),

    # Static URL
    url(r'', include('django.contrib.staticfiles.urls')),

    # Dajaxice URLs 
    url(r'^ajaxice', views.index),
    url(dajaxice_config.dajaxice_url, include('dajaxice.urls')),

    # Project-specific URLs
    url(r'^$', views.index, name='index'),
    url(r'', include('darkoob.social.urls', namespace='social', app_name='socials')),
    url(r'', include('darkoob.migration.urls', namespace='migration')),

    url(r'^book/', include('darkoob.book.urls', namespace='book')),
    url(r'^group/', include('darkoob.group.urls', namespace='group')),
    # Search 
    # TODO: Move to search application
    url(r'', include('darkoob.search.urls', namespace='search')),

    # url(r'^comments/', include('django.contrib.comments.urls')),

    url(r'^avatar/', include('avatar.urls')),
)

from django.conf import settings
media_root = getattr(settings, 'MEDIA_ROOT', '/media')    

urlpatterns += patterns('', 
url(r'^media/(?P<path>.*)$','django.views.static.serve',
    {'document_root': media_root})
)

darkoob/group/models.py
from django.db import models
from darkoob.social.models import User
from darkoob.book.models import Book, Quote
from django.utils import timezone
from djangoratings.fields import RatingField

class Group(models.Model):
    name = models.CharField(max_length=255)
    # comment = models.TextField(help_text=u'Description of Group') # <@vahid> i add quote instead, comment 
    admin = models.ForeignKey(User, related_name='admin_set')
    members = models.ManyToManyField(User, related_name='group_set', null=True)
    created_time = models.DateTimeField(default=timezone.now(), db_index=True)
    thumb =  models.ImageField(upload_to='groups/', null=True, blank=True)
    quote = models.ForeignKey(Quote, related_name='group_set', blank=True, null=True, help_text=u'Quote of Group')

    def __unicode__(self):
        return unicode(self.name)

class Schedule(models.Model):
    group = models.ForeignKey(Group, db_index=True)
    book = models.ForeignKey(Book, db_index=True)
    submitted_time = models.DateTimeField(default=timezone.now(), db_index=True)

    def __unicode__(self):
        return unicode("%s - %s" % (self.group.name, self.book.title))

class Deadline(models.Model):
    schedule = models.ForeignKey(Schedule)
    from_page = models.PositiveIntegerField()
    to_page = models.PositiveIntegerField()
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()
    submitted_time = models.DateTimeField(default=timezone.now())

    def __unicode__(self):
        return unicode("%s, %s from page %g to %g" % (
            self.schedule.group.name,
            self.schedule.book.title,
            self.from_page,
            self.to_page,
        ))

class Post(models.Model):
    user = models.ForeignKey(User, related_name='group_post_set')
    group = models.ForeignKey(Group)
    text = models.TextField()
    submitted_time = models.DateTimeField(default=timezone.now(), db_index=True)
    noks = RatingField(range=1, can_change_vote=True, allow_delete=True, allow_anonymous=False)

    def __unicode__(self):
        return unicode("user %s"% self.user_id)

darkoob/group/forms.py
from django import forms
from django.utils.translation import ugettext as _
from django.contrib.auth.forms import AuthenticationForm

class GroupForm(forms.Form):
    name = forms.CharField(
        max_length=30,
        widget=forms.TextInput(attrs={
            'placeholder': _('Group Name'),
            'class': 'input-medium ',
            'required': '',
        })
    )
    members = forms.CharField(required=False, widget=forms.HiddenInput())


class NewScheduleForm(forms.Form):
    book = forms.CharField(required=True, widget=forms.HiddenInput())

darkoob/group/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, render_to_response
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.utils.text import slugify
from django.utils import timezone
from django.template import RequestContext
from django.db import transaction

from darkoob.group.forms import GroupForm, NewScheduleForm
from darkoob.group.models import Group
from darkoob.book.models import Quote
from darkoob.social.forms import NewPostForm
from darkoob.group.models import Post

def group(request, group_id, group_slug):
    template = 'group/group_page.html'

    group = Group.objects.get(id=group_id)
    quote = Quote.get_random_quote()
    if request.is_ajax():
        template = 'post/posts.html'

    if group and group_slug == slugify(group.name):
        #group.admins = group.admin.admin_set.all()
        #group.members = group.members.all()

        is_member = False
        if group in request.user.group_set.all():
            is_member = True

        posts = Post.objects.filter(group=group).order_by("-submitted_time").all()

        # Calculate Deadlines for group
        book_deadlines = []
        for schedule in group.schedule_set.all():
            deadline_set = schedule.deadline_set.exclude(end_time__lte=timezone.now())
            for i in range(len(deadline_set)):
                deadline_set[i].time_percentage = (timezone.now() - deadline_set[i].start_time).total_seconds()  / (deadline_set[i].end_time - deadline_set[i].start_time).total_seconds() * 100
            if deadline_set:
                book_deadlines.append([ schedule.book , deadline_set])

        # Is this user admin of group?
        is_admin = False
        if request.user.id == group.admin.id:
            is_admin = True

        return render(request, template, {
            'group': group,
            'posts': posts,
            'quote': quote,
            'new_post_form': NewPostForm,
            'is_member': is_member,
            'is_admin': is_admin,
            'book_deadlines': book_deadlines,
            'schedule_form': NewScheduleForm(),
        })

    else:
        return HttpResponse("Group Is not exist!")

@login_required
def create_group(request):
    if request.method == 'POST':
        form = GroupForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            if not request.user.userprofile.quote:
                group = Group(name=cd['name'], admin=request.user)
            else:
                group = Group(name=cd['name'], admin=request.user, quote=request.user.userprofile.quote)
            group.save()
            for member in cd['members'].strip(',').split(','):
                try:
                    user = User.objects.get(username=member)
                    if user.id != request.user.id:
                        group.members.add(user)
                except:
                    pass
            group.save()
            groups = request.user.group_set.all()
            admin_groups = request.user.admin_set.all()
            return HttpResponseRedirect('/group/%i/%s'%(group.id,slugify(group.name)))

    else:
        form = GroupForm()
        groups = request.user.group_set.all()
        admin_groups = request.user.admin_set.all()
        return render(request, 'group/create_group.html', {'form': form, 'groups': groups, 'admin_groups': admin_groups })

@login_required
def members(request):
    pass

@login_required
def schedules(request):
    pass

@login_required
def add_schedule(request, group_id, group_slug):
    group = Group.objects.get(id=group_id)
    if group and group_slug == slugify(group.name):
        if request.method == 'POST':
            form = NewScheduleForm(request.POST)
            if group.admin.id == request.user.id:
                if form.is_valid():
                    cd = form.cleaned_data
                    book = Book.objects.get(name=cd['book'])
                    if book:
                        schedule = Schedule(group.id, book.id)
                        schedule.save()
                    groups = request.user.group_set.all()
                    admin_groups = request.user.admin_set.all()
                    return HttpResponseRedirect('/group/%i/%s'%(group.id,slugify(group.name)))
            else:
                pass
                # Permisson Denied
        else:
            if group.admin.id == request.user.id:
                form = NewScheduleForm()
                groups = request.user.group_set.all()
                admin_groups = request.user.admin_set.all()
                return render(request, '/group/add_schedule.html', {'form': form, 'groups': groups, 'admin_groups': admin_groups, 'group': group })
            else:
                pass
                #permisson denied

darkoob/group/templates/group/add_schedule.html
{% extends "social/home.html" %}
{% load staticfiles %}
{% block css %}
{{ block.super }}
<link rel="stylesheet" type="text/less" href="{% static "/static/css/profile_base_style.less" %}">
<link rel="stylesheet" type="text/less" href="{% static "/static/css/home_style.less" %}">
{% endblock css %}



{% block title %}Group{% endblock title %}

{% block main %}
<div class="row-fluid">
  <div class="span12">
    <div class="row-fluid">
      <div class="span12">
        <div class="simple-box">
          <p>

          </p>
          <form id="add_schedule_form" action='{% url "group:add_schedule" group.id group.name|slugify %}' method='post' class="form-inline">
           {% csrf_token %}
           {{ form.book }}
           <button type="button" id="add_schedule_button" onmousedown="#" class="btn btn-primary">Add Schedule</button>
         </form>
         <link rel="stylesheet" type="text/less" href="{% static "/static/css/typeahead_suggestion_with_photo.css" %}">
         <script src="{% static "/static/js/underscore.min.js" %}"></script>

         <input
         type="text"
         id="title-look"
         class="span6 typeahead"
         placeholder="Book Title"
         autocomplete="off"
         data-provide="typeahead"
         />

         <script src="{% static "/static/js/add_schedule.js" %}"></script>
         <script src="{% static "/static/js/book_typeahead_suggestion.js" %}"></script>

       </div>
     </div> <!-- span12 -->
   </div> <!-- row -->
 </div> <!-- span -->
</div> <!-- row -->
{% endblock main %}

darkoob/group/templates/group/create_group.html
{% extends "social/home.html" %}
{% load staticfiles %}
{% block css %}
{{ block.super }}
<link rel="stylesheet" type="text/less" href="{% static "/static/css/profile_base_style.less" %}">
<link rel="stylesheet" type="text/less" href="{% static "/static/css/home_style.less" %}">
{% endblock css %}



{% block title %}Group{% endblock title %}

{% block main %}
<div class="row-fluid">
  <div class="span12">
    <div class="row-fluid">
      <div class="span12">
        <div class="simple-box">
          <p>

          </p>
          <form id="add_group_form" action='{% url "group:create_group" %}' method='post' class="form-inline">
           {% csrf_token %}
           {{ form.name }}
           {{ form.members }}
           <button type="button" id="add_group_button" onmousedown="load_members()" class="btn btn-primary">Create Group</button>
         </form>
         <link rel="stylesheet" type="text/less" href="{% static "/static/css/typeahead_suggestion_with_photo.css" %}">
         <script src="{% static "/static/js/underscore.min.js" %}"></script>
        <b>Add primitive users before create</b>
        <br />

        You can select users and join them to your group.
        Only type username and press enter.
        <br />
         <div id="added-users"></div>
         
         <br/>
         <input
         type="text"
         id="user-look"
         class="span6 typeahead"
         placeholder="Username"
         autocomplete="off"
         data-provide="typeahead"
         />

         <script src="{% static "/static/js/create_group.js" %}"></script>
         <script src="{% static "/static/js/user_typeahead_suggestion.js" %}"></script>

       </div>
     </div> <!-- span12 -->
   </div> <!-- row -->
 </div> <!-- span -->
</div> <!-- row -->
{% endblock main %}

darkoob/group/templates/group/group_page.html
{% extends "base/profile_base.html" %}

{% load staticfiles %}
{% load thumbnail %}
{% load avatar_tags %}
{% load kwacros %}
{% loadkwacros "base/macros.html" %}

{% block css %}
{{ block.super }}
<link rel="stylesheet" type="text/less" href="{% static "/static/css/home_style.less" %}">
<link rel="stylesheet" type="text/less" href="{% static "/static/css/page.less" %}">
{% endblock css %}

{% block js %}
{{ block.super }}
{% endblock js %}

{% block title %}Group{% endblock title %}

{% block sidebar %}
<div class="row-fluid">
  <div class="span12">
    <ul class="nav nav-tabs nav-stacked left-nav">
      <li>
        <a href="{% url 'group:members' %}"><i class="icon-user"></i> Members<i class="icon-chevron-right" style="float:right"></i></a>
      </li>

      <li>
        <a href="{% url 'group:schedules' %}"><i class="icon-tasks"></i> Schedules
          <i class="icon-chevron-right" style="float:right"></i></a>
      </li>
    </ul>
    {% usekwacro deadline_box book_deadlines=book_deadlines is_admin=is_admin%}
     <div class="row-fluid">
      <h4 class="sidebox-head">MEMBERS</h4>
      <div class="span12 simple_box members">
        <ul class="thumbnails">
          {% for member in group.members.all|slice:":10" %}
            <li class="span2">
              {% usekwacro user_details user_=member placement='top' %}
                <a class="thumbnail">{% avatar member %}</a>
              </div>
            </li>
          {% endfor %}
        </ul>
      </div> <!-- span10 -->
    </div> <!-- row -->
  </div> <!-- span12 -->
</div> <!-- row -->
{% endblock sidebar %}

{% block main %}
<div class="row-fluid">
  <div class="span11 offset1">
    <div class="row-fluid">
      <div class="span12">
        {% usekwacro top_quote quote_=group.quote %}
      </div> <!-- span12 -->
    </div> <!-- row -->

    <div class="row-fluid">
      <div class="span12">
        <div class="details group-details">
          <div class="row-fluid">
            <div class="span2">
              <div class="thumb">
                {% thumbnail group.thumb "100x100" crop="center" as im %}
                  <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}"/>
                {% empty %}
                  <img src="{% static "/static/img/default-group.png" %}" width="100" height="100"/>
                {% endthumbnail %}
              </div>
            </div>
            <div class="span10">
              <div class="row-fluid">
                <div class="span5">
                  <h4>{{ group.name }}</h4>
                </div>
              </div>
                
              <div class="row-fluid stats">
                <div class="span10">
                  <div class="info-block"><a href="{% url 'group:members' %}">{{ group.members.all|length }} members</a></div>
                  <div class="info-block"><a href="{% url 'group:schedules' %}">{{ group.schedules|length }} schedules</a></div>
                  <div class="info-block"><a href="{% url 'group:schedules' %}">{{ group.deadlines|length }} deadlines</a></div>
                </div>
                <div class="span1 offset1">
                  <button id="group-toggle-btn" class="btn btn-primary btn-mini pull-right"
                    onclick="Dajaxice.darkoob.group.group_toggle(group_toggle_cb,
                    {group_id: {{ group.id }},
                    user_id: {{ user.id }},
                    is_member: {% if is_member %}true{% else %}false{% endif %}})">
                    {% if is_member %}Leave{% else %}Join{% endif %}
                  </button>

              </div>
            </div> <!-- span10 -->
          </div> <!-- row -->
        </div> <!-- details -->
      </div> <!-- span12 -->
    </div> <!-- row -->

    <script type="text/javascript">
      function change_group_post_type(type){
          $('#group_post_form').toggle();
          $('#group_schedule_form').toggle();
        $('.new-post-icon').each(function(index,value){
          if (index==type){
            $(this).attr('class','new-post-icon new-post-icon-active');
          }else{
            $(this).attr('class','new-post-icon');
          }
        })
      }
    </script>

    <div class="row-fluid">
      <div class="span1">
        <img class="new-post-icon new-post-icon-active" src="{% static "/static/img/Pen-black-32.png" %}" alt="Text" onclick="change_group_post_type(0);" />
        <img class="new-post-icon" src="{% static "/static/img/Cronometer-black-32.png" %}" alt="Deadline" onclick="change_group_post_type(1);"/>
      </div>
      <div class="span11">
        <div class="sidebox">
          <div id="group_post_form" class="row-fluid">
            <div class="span9 new_post_container">
              <form  method="post" action="{% url "social:new_post" %}">
                {% csrf_token %}
                {{ new_post_form.text }}
              </form>
            </div>
            <div class="span1 new_post_button">
              <button class="btn btn-inverse" onclick="Dajaxice.darkoob.group.submit_post(Dajax.process, {'text': $('#id_text').val(), 'group_id': {{ group.id }} })">Post</button>
            </div>
          </div> <!-- row -->

          <div id="group_schedule_form" class="row-fluid" style="Display:None">
            <div class="span9 new_post_container">
              <form  method="post" action="{% url "social:new_post" %}">
                {% csrf_token %}
                {{ schedule_form.book }}
              </form>
            </div>
            <div class="span1 new_post_button">
              <button class="btn btn-inverse" onclick="Dajaxice.darkoob.group.submit_post(Dajax.process, {'text': $('#id_text').val(), 'group_id': {{ group.id }} })">SCHEDULE</button>
            </div>
          </div> <!-- row -->

        </div> <!-- sidebox -->
      </div> <!-- span11 -->
    </div> <!-- row -->


      <div id="id_new_post_position">
      </div>

    <div class="row-fluid">
      <div class="span12">
        {% include "post/posts.html" %}
      </div> <!-- span12 -->
    </div> <!-- row -->
  </div> <!-- span -->
</div> <!-- row -->
{% endblock main %}

{% block bottom_js %}
{{ block.super }}
<script type="text/javascript" src="{% static "/static/js/group.js" %}"></script>
{% endblock bottom_js %}